CREATE DATABASE MVC_PRACTICE;
USE MVC_PRACTICE;

CREATE TABLE MVC_PRACTICE(
    WRITER CHAR(4),
    EMAIL INT NOT NULL,
    SUBJECT DATE, 
    PASSWORD CHAR(5), 
    AMOUNT CHAR(5),
    PRIMARY KEY (PRODUCTNAME)
);